import { Inter, Chela_One } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "../context/AuthContext";
import Navbar from "./components/Navbar";

const inter = Inter({ subsets: ["latin"] });

const chela_one = Chela_One({
  subsets: ["latin"],
  display: "swap",
  weight: "400",
  variable: "--font-chela-one",
});

export const metadata = {
  title: "StreamLink",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${chela_one}`}>
        <AuthProvider>
          <Navbar />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
